# Flask Application Configuration
app:
  name: "Microstructural Analysis Portal"
  debug: true
  port: 5000
  host: "127.0.0.1"

# Image Processing Settings
image:
  max_size: 10485760  # 10MB in bytes
  allowed_extensions:
    - .jpg
    - .jpeg
    - .png
    - .bmp
  max_dimension: 1200

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s %(levelname)s: %(message)s"
  file: "app.log"

# Feature Flags
features:
  enable_feedback: true
  enable_analysis: true
  enable_ml_models: false  # Will be enabled when ML models are integrated 