import os

from flask import Blueprint, send_file

from ...config import Config

"""Routes for serving processed data files to the user."""

bp = Blueprint("download", __name__)
config = Config()


@bp.route("/download_processed_data")
def download_processed_data() -> tuple:
    """Serve the processed EBSD map generated by the demo model."""
    try:
        file_path = config.processed_data_path
        if not os.path.exists(file_path):
            return "Processed file not found.", 404
        return send_file(
            file_path,
            mimetype="image/png",
            as_attachment=True,
            download_name=os.path.basename(file_path),
        )
    except Exception:
        return "Internal Server Error", 500
